training:
  num_epochs: 10
  save_name: "trained_ResNet50_flowers.pt"

#dataset names: "Flowers", "Cub", "Dogs", "Airplanes", "Food"

dataset: "Flowers"

#model name: "CLIP", "Vgg19", "ResNet50"

model: "ResNet50"


data:
  batch_size_train: 32
  batch_size_test: 256
  num_workers: 4
  output_dim: 102
  path_root: None

logger:
  wandb: True

competition: False